name: build and deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Uses Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn -v
      - run: yarn
      - run: yarn build
      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws --version
      - run: aws s3 cp s3://flood-game ./build --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
